#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")


env_tracy = env_modules.Clone()

thirdparty_dir = "#thirdparty/tracy/"
thirdparty_sources = ["#thirdparty/tracy/public/TracyClient.cpp"]
thirdparty_obj = []

env_tracy.Prepend(CPPPATH=[thirdparty_dir])
env_tracy.disable_warnings()
env_tracy.add_source_files(thirdparty_obj, thirdparty_sources)
env.modules_sources += thirdparty_obj

# Godot source files
module_obj = []
env_tracy.add_source_files(module_obj, "*.cpp")
env.modules_sources += module_obj

# Needed to force rebuilding the module files when the thirdparty library is updated.
env.Depends(module_obj, thirdparty_obj)
